Name : Prince Titiya
ID   : 202318010    
This segment of the assignment is designed to enhance understanding of the API call process and dataset creation. 
Utilize any freely available API endpoint on RapidAPI to generate a dataset.

In [2]:
import requests
import pandas as pd  # Import pandas library

def fetch_quotes():
    url = "https://apidojo-yahoo-finance-v1.p.rapidapi.com/auto-complete"
    querystring = {"q": "tesla", "region": "US"}

    headers = {
        "X-RapidAPI-Key": "aa48581c80msh6dc13c85a681dc4p143375jsn17249c4b6104",
        "X-RapidAPI-Host": "apidojo-yahoo-finance-v1.p.rapidapi.com"
    }

    response = requests.get(url, headers=headers, params=querystring)
    quotes = response.json().get('quotes', []) # Extracting data from response
    df = pd.DataFrame(quotes)
    return df

dfs = [fetch_quotes() for i in range(50)]    # iterating 50 times throught function and appends all dataframes
final_df = pd.concat(dfs, ignore_index=True)

final_df  #result

,exchange,shortname,quoteType,symbol,index,score,typeDisp,longname,exchDisp,sector,sectorDisp,industry,industryDisp,dispSecIndFlag,isYahooFinance
0,NMS,"Tesla, Inc.",EQUITY,TSLA,quotes,1376361.0,Equity,"Tesla, Inc.",NASDAQ,Consumer Cyclical,Consumer Cyclical,Auto Manufacturers,Auto Manufacturers,True,True
1,NGM,T-REX 2X Long Tesla Daily Targe,ETF,TSLT,quotes,22044.0,ETF,NaN,NASDAQ,NaN,NaN,NaN,NaN,NaN,True
2,NEO,"TESLA, INC. CDR (CAD HEDGED)",EQUITY,TSLA.NE,quotes,21517.0,Equity,"Tesla, Inc.",NEO,Consumer Cyclical,Consumer Cyclical,Auto Manufacturers,Auto Manufacturers,NaN,True
3,NEO,TESLA (TSLA) YIELD SHARES PURPO,ETF,YTSL.NE,quotes,20914.0,ETF,Tesla (TSLA) Yield Shares Purpose ETF,NEO,NaN,NaN,NaN,NaN,NaN,True
4,GER,"TESLA INC. DL -,001",EQUITY,TL0.DE,quotes,20677.0,Equity,"Tesla, Inc.",XETRA,Consumer Cyclical,Consumer Cyclical,Auto Manufacturers,Auto Manufacturers,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,NEO,"TESLA, INC. CDR (CAD HEDGED)",EQUITY,TSLA.NE,quotes,21517.0,Equity,"Tesla, Inc.",NEO,Consumer Cyclical,Consumer Cyclical,Auto Manufacturers,Auto Manufacturers,NaN,True
346,NEO,TESLA (TSLA) YIELD SHARES PURPO,ETF,YTSL.NE,quotes,20914.0,ETF,Tesla (TSLA) Yield Shares Purpose ETF,NEO,NaN,NaN,NaN,NaN,NaN,True
347,GER,"TESLA INC. DL -,001",EQUITY,TL0.DE,quotes,20677.0,Equity,"Tesla, Inc.",XETRA,Consumer Cyclical,Consumer Cyclical,Auto Manufacturers,Auto Manufacturers,NaN,True
348,LSE,LEVERAGE SHARES PUBLIC LIMITED,EQUITY,TSL3.L,quotes,20445.0,Equity,Leverage Shares 3x Tesla ETP Securities,London,NaN,NaN,NaN,NaN,NaN,True
349,NGM,T-Rex 2X Inverse Tesla Daily Ta,ETF,TSLZ,quotes,20281.0,ETF,T-Rex 2X Inverse Tesla Daily Target ETF,NASDAQ,NaN,NaN,NaN,NaN,NaN,True